# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User
bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds
bind = Super+Shift, Q, exec, ~/.config/hypr/custom/scripts/KillActiveProcess.sh
unbind = Super, Slash
bindd = Super, H, Toggle cheatsheet, global, quickshell:cheatsheetToggle # Toggle cheatsheet

bind = Super+Shift, code:10, movetoworkspace, 1
bind = Super+Shift, code:11, movetoworkspace, 2
bind = Super+Shift, code:12, movetoworkspace, 3
bind = Super+Shift, code:13, movetoworkspace, 4
bind = Super+Shift, code:14, movetoworkspace, 5
bind = Super+Shift, code:15, movetoworkspace, 6
bind = Super+Shift, code:16, movetoworkspace, 7
bind = Super+Shift, code:17, movetoworkspace, 8
bind = Super+Shift, code:18, movetoworkspace, 9
bind = Super+Shift, code:19, movetoworkspace, 10

unbind = Super, B
unbind = Super, W
unbind = Super+Shift, T
unbind = Super+Shift, X
unbind = Super, D
unbind = Super, F
bind = Super, W, global, quickshell:sidebarLeftToggle # [hidden]
bind = Super, B, exec, $browser # Browser
bind = Super+Shift, T, global, quickshell:regionOcr # Character recognition >> clipboard
bind = Super+Shift, X, global, quickshell:screenTranslate # Translate screen content
bind = Super, F, fullscreen, 1 # Maximize
bind = Super+Shift, F, fullscreen, 0 # Fullscreen